### ISSUE TITLE
I am unable to minitor db2 databases by using Nagios tool

### ISSUE THREAD

**Issue by sudheer1432** [angoca/monitor-db2-with-nagios#44]
Hi Team,

 I have a db2 production system which is being monitored by Nagios tool and it is configured by other teammate who is not here .
I tried by fetching the script like disk_utilization and some other scripts but I don't find in the server where we installed Nagios but database level monitoring scripts are present in database machine but unfortunately those are present in two different locations.
I would like to find from which path those are monitoring.

Kindly let me know If you need any additional information.

Thanks In Advance !!!

**Comment by angoca** [comment]
Hi,

Are you using our scripts? https://github.com/angoca/monitor-db2-with-nagios
We do not have anyone called disk_utilisation, it seems check plugins from another project.

If you want to know which script are you running, you can check that from "ps -ef", also by looking at the PATH variable from the user executing the scripts.
There are also a NRPE configuration, or the SSH remote execution.

Regards,

**Comment by sudheer1432** [comment]
Hi,

Thanks for your information.

I have a dedicated system which we are using to monitor databases server file system alerts , database level monitoring by using Nagios Plugins.

but I could see few database level scripts are defined in another server called production database server.
My question was how do we find those scripts from which machine they are running ?
1) Could you please provide me the steps to configure nagios and monitor OS level file system monitoring and database level monitoring.
2) I have a dedicated system which is running on Linux machine, in this machine I have Nagios bimaries running and suppose If I want to monitor db2 databases which are are running on another machine do I need to install Nagios in other machine as well.

In my current organization somebody installed on these machine and now no body he having any idea on this and moreover I do not have an experience on this Nagios tool
Could you please let me know so that I can configure nagios for another db2 boxes.

Thanks,

**Comment by angoca** [comment]
For Nagios installation, you can post the answer in dedicated forums like https://support.nagios.com/forum

For the DB2 scripts that this project provides, we can help you; however, we can only do that if you know how your environment is configured. We do not provide instructions about how to configure Nagios environment.
